import type { HighlightCardData } from './types';

const A = '/highlights';

export const FIGMA_HIGHLIGHTS: HighlightCardData[] = [
  {
    id: 'figma-godzilla-1',
    title: 'Godzilla 🧨',
    author: 'Dodoeu',
    authorAvatarSrc: `${A}/avatar-dodoeu.png`,
    thumbnailSrc: `${A}/thumb-godzilla.png`,
    href: 'https://youtu.be/JWlBCQIQags?si=-6gGHkedcxMRwoF-',
    likeCount: 273,
    isLiked: true,
    source: 'figma',
  },
  {
    id: 'figma-piz-1',
    title: 'IL MIGLIOR HIGHLIGHTS...',
    author: 'Piz',
    authorAvatarSrc: `${A}/avatar-piz.png`,
    thumbnailSrc: `${A}/thumb-piz.png`,
    href: 'https://youtu.be/HxRTrHyWB0Y?si=VdsoQIswI9eOlHG5',
    likeCount: 655,
    source: 'figma',
  },
  {
    id: 'figma-clix-1',
    title: 'Never Change 💔 | Clix',
    author: 'Clix',
    authorAvatarSrc: `${A}/avatar-clix.png`,
    thumbnailSrc: `${A}/thumb-clix.png`,
    href: 'https://youtu.be/CtK-fV6TsBY?si=6zOsv5SjhmzvPEHJ',
    likeCount: 1200,
    isLiked: true,
    source: 'figma',
  },
  {
    id: 'figma-peterbot-1',
    title: '1st FNCS GRAND FINALS...',
    author: 'Peterbot',
    authorAvatarSrc: `${A}/avatar-peterbot.png`,
    thumbnailSrc: `${A}/thumb-peterbot.png`,
    href: 'https://youtu.be/K5MZeXFPsGc?si=axxBNUHOC5f-Ty1f',
    likeCount: 5300,
    source: 'figma',
  },
  {
    id: 'figma-eomzo-1',
    title: 'Pricey 🪙 | Eomzo Highlig...',
    author: 'Eomzo',
    authorAvatarSrc: `${A}/avatar-eomzo.png`,
    thumbnailSrc: `${A}/thumb-eomzo.png`,
    href: 'https://youtu.be/4xv3O_VrW0M?si=KE0tHu7KU0qFt0ov',
    likeCount: 973,
    isLiked: true,
    source: 'figma',
  },
  {
    id: 'figma-malibuca-1',
    title: 'Malibuca | Highlights #2',
    author: 'Malibuca',
    authorAvatarSrc: `${A}/avatar-malibuca.png`,
    thumbnailSrc: `${A}/thumb-malibuca.png`,
    href: 'https://youtu.be/CtK-fV6TsBY?si=6zOsv5SjhmzvPEHJ',
    likeCount: 802,
    isLiked: true,
    source: 'figma',
  },
  {
    id: 'figma-godzilla-2',
    title: 'Godzilla 🧨',
    author: 'Dodoeu',
    authorAvatarSrc: `${A}/avatar-dodoeu.png`,
    thumbnailSrc: `${A}/thumb-godzilla.png`,
    href: 'https://youtu.be/JWlBCQIQags?si=-6gGHkedcxMRwoF-',
    likeCount: 273,
    isLiked: true,
    source: 'figma',
  },
  {
    id: 'figma-piz-2',
    title: 'IL MIGLIOR HIGHLIGHTS...',
    author: 'Piz',
    authorAvatarSrc: `${A}/avatar-piz.png`,
    thumbnailSrc: `${A}/thumb-piz.png`,
    href: 'https://youtu.be/HxRTrHyWB0Y?si=VdsoQIswI9eOlHG5',
    likeCount: 655,
    source: 'figma',
  },
  {
    id: 'figma-clix-2',
    title: 'Never Change 💔 | Clix',
    author: 'Clix',
    authorAvatarSrc: `${A}/avatar-clix.png`,
    thumbnailSrc: `${A}/thumb-clix.png`,
    href: 'https://youtu.be/CtK-fV6TsBY?si=6zOsv5SjhmzvPEHJ',
    likeCount: 1200,
    isLiked: true,
    source: 'figma',
  },
  {
    id: 'figma-peterbot-2',
    title: '1st FNCS GRAND FINALS...',
    author: 'Peterbot',
    authorAvatarSrc: `${A}/avatar-peterbot.png`,
    thumbnailSrc: `${A}/thumb-peterbot.png`,
    href: 'https://youtu.be/K5MZeXFPsGc?si=axxBNUHOC5f-Ty1f',
    likeCount: 5300,
    source: 'figma',
  },
  {
    id: 'figma-eomzo-2',
    title: 'Pricey 🪙 | Eomzo Highlig...',
    author: 'Eomzo',
    authorAvatarSrc: `${A}/avatar-eomzo.png`,
    thumbnailSrc: `${A}/thumb-eomzo.png`,
    href: 'https://youtu.be/4xv3O_VrW0M?si=KE0tHu7KU0qFt0ov',
    likeCount: 655,
    isLiked: true,
    source: 'figma',
  },
  {
    id: 'figma-malibuca-2',
    title: 'Malibuca | Highlights #2',
    author: 'Malibuca',
    authorAvatarSrc: `${A}/avatar-malibuca.png`,
    thumbnailSrc: `${A}/thumb-malibuca.png`,
    href: 'https://youtu.be/CtK-fV6TsBY?si=6zOsv5SjhmzvPEHJ',
    likeCount: 1200,
    isLiked: true,
    source: 'figma',
  },
];

export const FIGMA_WINNER: HighlightCardData = {
  ...FIGMA_HIGHLIGHTS[3],
  id: 'figma-winner-peterbot',
  rank: 1,
};

export const FIGMA_RANKED_NOMINEES: HighlightCardData[] = [
  {
    ...FIGMA_HIGHLIGHTS[3],
    id: 'figma-rank-1-peterbot',
    rank: 1,
  },
  {
    ...FIGMA_HIGHLIGHTS[2],
    id: 'figma-rank-2-clix',
    rank: 2,
  },
  {
    ...FIGMA_HIGHLIGHTS[4],
    id: 'figma-rank-3-eomzo',
    rank: 3,
  },
  {
    ...FIGMA_HIGHLIGHTS[5],
    id: 'figma-rank-4-malibuca',
    rank: 4,
  },
];
